name: Jest Automatic Testing

on: pull_request_target

jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install all dependencies
        working-directory: client
        run: npm install

      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" > client/.env.local
          echo "NEXT_PUBLIC_SUPABASE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}" >> client/.env.local
          echo "NEXT_PUBLIC_SUPABASE_KEY=${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_ID }}" >> client/.env.local
          echo "NEXT_PUBLIC_SUPABASE_KEY=${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET }}" >> client/.env.local

      - name: Run Jest Tests
        working-directory: client
        run: npm test
